name: datexp

services:
    backend:
        container_name: datexp-backend
        ports:
            - 5000:5000
        restart: unless-stopped
        env_file:
            - ./server/.env
        networks:
            - datexp
        image: chukevh/datexp-server:latest
    frontend:
        container_name: datexp-frontend
        ports:
            - 80:8080
        restart: unless-stopped
        env_file:
            - ./frontend/.env
        networks:
            - datexp
        image: chukevh/datexp-frontend:latest
networks:
    datexp:
        name: datexp

