name: datexp

services:
    backend:
        container_name: datexp-backend
        build: 
          context: ./server
          dockerfile: Dockerfile
        ports:
            - 5000:5000
        restart: unless-stopped
        env_file:
            - ./server/.env
        networks:
            - datexp
        image: chukevh/datexp-server:latest
    frontend:
        container_name: datexp-frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
            args:
                VITE_GOOGLE_API_KEY: AIzaSyA1Z6aZf4dOLU706a79e99kLf3WA_n3qHE
        ports:
            - 80:8080
        restart: unless-stopped
        env_file:
            - ./frontend/.env
        networks:
            - datexp
        image: chukevh/datexp-frontend:latest
networks:
    datexp:
        name: datexp

