name: datexp CD
on:
  workflow_run:
    workflows: ["datexp CI"]
    types: [completed]

jobs:
  on-CI-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Deploy
        uses: actions/checkout@v4
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.SSH_HOST}}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 400 private_key
          ssh -i private_key ${HOSTNAME} << EOF
            cd app/dateXP
            docker compose stop
            docker compose rm -f
            docker compose pull
            docker compose up -d
          EOF

